### ISSUE TITLE
Race condition/unclean test_run config file.

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#129]
When building pav test run object (to get statuses) this can happen:
```Unknown error running command wait: Expecting value: line 1 column 1 (char 0).
Traceback (most recent call last):
  File "/opt/moon-cluster/pav/pavilion2/bin/pav.py", line 236, in main
    sys.exit(cmd.run(pav_cfg, args))
  File "/opt/moon-cluster/pav/pavilion2/lib/pavilion/plugins/commands/wait.py", line 61, in run
    tmp_statuses = status.get_statuses(pav_cfg, args, self.errfile)
  File "/opt/moon-cluster/pav/pavilion2/lib/pavilion/plugins/commands/status.py", line 100, in get_s
tatuses
    series.TestSeries.from_id(pav_cfg, test_id).tests)
  File "/opt/moon-cluster/pav/pavilion2/lib/pavilion/series.py", line 127, in from_id
    tests.append(TestRun.load(pav_cfg, test_id=test_id))
  File "/opt/moon-cluster/pav/pavilion2/lib/pavilion/test_run.py", line 275, in load
    config = cls._load_config(path)
  File "/opt/moon-cluster/pav/pavilion2/lib/pavilion/test_run.py", line 332, in _load_config
    return json.load(config_file)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I think it's because the config or other test_run files are in the midst of being rewritten when they're read. These writes need to be done atomically.

**Comment by Paul-Ferrell** [comment]
Actually, this needs to be handled correctly when loading tests for the status (and other similar commands).

**Comment by Paul-Ferrell** [comment]
I guess we could do it atomically too. Write the file to a tmp location then move it.
