### ISSUE TITLE
pav wait bug

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#197]
Unknown error running command wait: Expecting value: line 1 column 1 (char 0).
Traceback (most recent call last):
  File "/usr/projects/hpctest/pav2-next/src/bin/pav.py", line 229, in main
    sys.exit(cmd.run(pav_cfg, args))
  File "/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/wait.py", line 78, in run
    stats = status.get_statuses(pav_cfg, args, self.errfile)
  File "/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/status.py", line 151, in get_statuses
    test_list = get_tests(pav_cfg, args, errfile)
  File "/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/status.py", line 123, in get_tests
    test_id).tests)
  File "/usr/projects/hpctest/pav2-next/src/lib/pavilion/series.py", line 127, in from_id
    tests.append(TestRun.load(pav_cfg, test_id=test_id))
  File "/usr/projects/hpctest/pav2-next/src/lib/pavilion/test_run.py", line 377, in load
    config = cls._load_config(path)
  File "/usr/projects/hpctest/pav2-next/src/lib/pavilion/test_run.py", line 438, in _load_config
    return json.load(config_file)
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback logged to /usr/projects/hpctest/pav2-next/working_dir/exceptions.log

**Comment by Paul-Ferrell** [comment]
It's the wait command. 
1. When get_tests() loads a test, we should catch any errors. 
2. The problem I'm guessing is that we're trying to read an incompletely written config file. The config is saved twice. Once when the object is originally created, and once when it's finalized. `wait` is catching the partially written file during `finalize()`. 
  - This file needs to be written atomically. 
  - In fact that should be the case for all files written by test_run.
