### ISSUE TITLE
Pav Run $test-does-not-exist

### ISSUE THREAD

**Issue by CalvinDSeamons** [hpc/pavilion2#242]
On latest master branch running `pav run fsgwgdsfgdsfg` (a yaml that isn't there) you get the following. 
```bash
pav run fsgwgdsfgdsfg
Unknown error running command run: Could not find test suite fsgwgdsfgdsfg. Looked in these locations: [PosixPath('/users/calvindseamons/.pavilion')].
Traceback (most recent call last):
  File "$PATH/git/pavilion2/bin/pav.py", line 118, in main
    sys.exit(cmd.run(pav_cfg, args))
  File "$PATH/git/pavilion2/lib/pavilion/plugins/commands/run.py", line 133, in run
    local_builds_only=getattr(args, 'local_builds_only', False))
  File "$PATH/git/pavilion2/lib/pavilion/plugins/commands/run.py", line 389, in _get_tests
    sys_vars=sys_vars,
  File "$PATH/git/pavilion2/lib/pavilion/plugins/commands/run.py", line 321, in _get_test_configs
    overrides
  File "$PATHgit/pavilion2/lib/pavilion/test_config/resolver.py", line 219, in load
    raw_tests = self.load_raw_configs(tests, host, modes)
  File "$PATH/git/pavilion2/lib/pavilion/test_config/resolver.py", line 339, in load_raw_configs
    .format(test_suite, self.pav_cfg.config_dirs))
pavilion.test_config.file_format.TestConfigError: Could not find test suite fsgwgdsfgdsfg. Looked in these locations: [PosixPath('$PATH/.pavilion')]
Traceback logged to $PATH/.pavilion/working_dir/exceptions.log
```

I recall that this was caught so the try/catch might have been deleted. If not, i assume that's all that's needed to make a nice error message. I can address this most likely this week unless someone else wants to fix it right now.

**Comment by Paul-Ferrell** [comment]
It was fixed at some point.
