### ISSUE TITLE
pav status --all with large limit throws an exception

### ISSUE THREAD

**Issue by nicholas-sly** [hpc/pavilion2#303]
```bash
[sly@xxxx 0000105]$ pav status --all -l 118
Unknown error running command status: 'str' object has no attribute 'strftime'.
Traceback (most recent call last):
  File "/users/sly/git/pavilion2/bin/pav.py", line 135, in run_cmd
    sys.exit(cmd.run(pav_cfg, args))
  File "/users/sly/git/pavilion2/lib/pavilion/plugins/commands/status.py", line 288, in run
    return print_status(test_statuses, self.outfile, args.json,
  File "/users/sly/git/pavilion2/lib/pavilion/plugins/commands/status.py", line 202, in print_status
    output.draw_table(
  File "/users/sly/git/pavilion2/lib/pavilion/output.py", line 495, in draw_table
    rows = dt_format_rows(rows, fields, field_info)
  File "/users/sly/git/pavilion2/lib/pavilion/output.py", line 595, in dt_format_rows
    data = info.get('transform', lambda a: a)(data)
  File "/users/sly/git/pavilion2/lib/pavilion/output.py", line 83, in get_relative_timestamp
    if now.strftime(format_[i]) != base_dt.strftime(format_[i]):
AttributeError: 'str' object has no attribute 'strftime'
Traceback logged to /users/sly/git/pavworking_dir/exceptions.log
[sly@xxxx 0000105]$ pav status
 Test statuses                                                                                                    
---------+-----------------------------------------+----------+--------------+--------------------------------------
 Test id | Name                                    | State    | Time         | Note                                 
---------+-----------------------------------------+----------+--------------+--------------------------------------
 117     | hello_mpi.gcc-openmpi.gcc-openmpi       | COMPLETE | Wed 16:31:44 | The test completed with result: PASS 
 118     | hello_mpi.cce-cray-mpich.cce-cray-mpich | COMPLETE | Wed 16:41:21 | The test completed with result: FAIL 
[sly@xxxx 0000105]$ pav --version
Pavilion 2.1.2
[sly@xxxx 0000105]$ cd /users/sly/git/pavilion2
[sly@xxxx pavilion2]$ git log | head
commit 0bbaf3cbbd581eb2a7ce07a3d10585aaf875d3e9
Author: Paul Ferrell <51765748+Paul-Ferrell@users.noreply.github.com>
Date:   Thu Jul 9 14:24:08 2020 -0600

    Show docs and other stuff. (#286)
    
    * Bug fixes from week of testing.
    
    * Added built-in profiling.
```

Limit actually on this particular machine seems to hit at 69 tests.  The command was able to print the status for the last 68 tests, but not 69.  Reach out to me for more information on the machine in this case.

**Comment by Paul-Ferrell** [comment]
It's not that the limit is large it just finds a bad set of test information.
