### ISSUE TITLE
Node list ValueError on cray

### ISSUE THREAD

**Issue by dmageeLANL** [hpc/pavilion2#320]
Running pavilion on trinitite, requesting standard partition 4 nodes, results in a RUN_ERROR.

Looking at `pav log kickoff <n>` shows this error. 

``` bash
ValueError: Invalid Node List: 'nid00[111,169-170,174]'. Syntax error in item 'nid00[111'. Node lists components be a hostname or hostname prefix followed by a range of node numbers. Ex: foo003,foo0[10-20],foo[103-104]
```

----

FULL TRACE:

```
Traceback (most recent call last):
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/bin/pav.py", line 135, in run_cmd
    sys.exit(cmd.run(pav_cfg, args))
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/plugins/commands/_run.py", line 46, in run
    var_man = self._get_var_man(test, sched)
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/plugins/commands/_run.py", line 102, in _get_var_man
    var_man.add_var_set('sched', sched.get_vars(sched_config))
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/test_config/variables.py", line 141, in add_var_set
    var_set = VariableSet(name, value_dict=value_dict)
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/test_config/variables.py", line 701, in __init__
    self._init_from_config(value_dict)
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/test_config/variables.py", line 710, in _init_from_config
    for key, value in value_dict.items():
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/var_dict.py", line 126, in <genexpr>
    return ((k, self[k]) for k in self.keys())
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/var_dict.py", line 104, in __getitem__
    self.data[key] = getattr(self, key)()
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/schedulers.py", line 64, in defer
    value = func(self)
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/plugins/sched/slurm.py", line 237, in test_node_list_short
    self.test_node_list().split(),
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/schedulers.py", line 64, in defer
    value = func(self)
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/plugins/sched/slurm.py", line 230, in test_node_list
    return self.alloc_node_list()
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/schedulers.py", line 64, in defer
    value = func(self)
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/plugins/sched/slurm.py", line 200, in alloc_node_list
    return ' '.join(Slurm.parse_node_list(os.getenv('SLURM_NODELIST')))
  File "/usr/projects/hpctest/dmagee/pav/pavilion2/lib/pavilion/plugins/sched/slurm.py", line 483, in parse_node_list
    .format(node_list, part)
```

**Comment by j-ogas** [comment]
I too am getting this error on the master branch of Trinitite. Note I am unable to roll back to the previous tag due to new config keys, e.g., `maintainer` etc., in my config.
