### ISSUE TITLE
Getting - NameError: name 'num' is not defined when running max function example.

### ISSUE THREAD

**Issue by coneheadusa** [hpc/pavilion2#363]
Following the max function example found on this page:
https://pavilion2.readthedocs.io/en/latest/plugins/expression_functions.html
I get an error "NameError: name 'num' is not defined
Below is the exact code I'm trying to run and the  commands I used to test
the example.  Please advise.
 ```
echo $PYTHONPATH
/home/uastest/rls/pavilion/src/pavilion2/lib
python3

>>> import max
>>> max.Max()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/uastest/.pavilion/plugins/functions/max.py", line 23, in __init__
    arg_specs=([num],)
NameError: name 'num' is not defined
```
max.py code:
```
from pavilion import expression_functions 
# All function plugins inherit from the 'FunctionPlugin' class

class Max(expression_functions.FunctionPlugin):

    # As with other plugin types, we override __init__ to provide the
    # basic information on our plugin.
    def __init__(self):

        super().__init__(
            # The name of our plugin and function
            name="max",

            # The short description shown when listing these plugins.
            description="Get the max of a list of numbers",

            # The arg_specs define how to auto-convert arguments to the
            # appropriate types. More on that below.
            # Note: (foo,) is a single item tuple containing foo.
            arg_specs=([num],)
        )

    # This method is the 'function' this plugin defines. It should take
    # arguments as defined by the arg_spec. It should also return one of the
    # types understood by Pavilion expressions (int, float, bool, string, or
    # lists/dicts containing only those types).
    @staticmethod
    def max(nums):
        """The docstring of the function will serve as its long
        documentation."""

        # We don't need to do any type checking, those conversions
        # will already be done for us (and will raise the appropriate
        # errors).
        return max(nums)
      
```

**Comment by Paul-Ferrell** [comment]
Oh, sorry to not get back to you sooner. You need to:
```python
from pavilion.expression_functions import num
```

**Comment by Paul-Ferrell** [comment]
I'll update the documentation to fix that.
