### ISSUE TITLE
Uncaught exceptions

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#380]
pav result with invalid test id
pav status with invalid test id

**Comment by Paul-Ferrell** [comment]
Traceback (most recent call last):
  File "/yellow/usr/projects/hpctest/pav2-next/src/bin/pav.py", line 139, in run_cmd
    sys.exit(cmd.run(pav_cfg, args))
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/show.py", line 349, in run
    return self._run_sub_command(pav_cfg, args)
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/commands.py", line 202, in _run_sub_command
    cmd_result = self.sub_cmds[cmd_name](self, pav_cfg, args)
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/show.py", line 615, in _result_parsers_cmd
    res_plugin = parsers.get_plugin(args.doc)
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/result/parsers.py", line 35, in get_plugin
    return _RESULT_PARSERS[name]
KeyError: 'cmd'
Traceback logged to /users/pflarr/.pavilion/working_dir/exceptions.log

**Comment by Paul-Ferrell** [comment]
Line 87 of result/base.py needs to be in a try except block, and store None/Null on failure.

```
Traceback (most recent call last):
  File "/yellow/usr/projects/hpctest/pav2-next/src/bin/pav.py", line 139, in run_cmd
    sys.exit(cmd.run(pav_cfg, args))
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/result.py", line 105, in run
    if not self.update_results(pav_cfg, tests, log_file):
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/result.py", line 264, in update_results
    regather=True, log_file=log_file)
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/test_run.py", line 954, in gather_results
    results = result.base_results(self)
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/result/base.py", line 87, in base_results
    results[key] = func(test)
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/result/base.py", line 50, in <lambda>
    'duration': (lambda test: (test.finished - test.started),
TypeError: unsupported operand type(s) for -: 'float' and 'NoneType'
```
