### ISSUE TITLE
pav wait error

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#391]
2021-03-03 13:25:25,973 {"traceback": "Traceback (most recent call last):\n  File \"/yellow/usr/projects/hpctest/pav2-next/src/bin/pav.py\", line 143, in run_cmd\n    sys.exit(cmd.run(pav_cfg, args))\n  File \"/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/wait.py\", line 77, in run\n    self.wait(pav_cfg, tests, end_time, args.out_mode)\n  File \"/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/wait.py\", line 95, in wait\n    test_obj = TestRun.load(pav_cfg, test_id)\n  File \"/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/test_run.py\", line 576, in load\n    config = cls._load_config(path)\n  File \"/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/test_run.py\", line 735, in _load_config\n    return json.load(config_file)\n  File \"/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python3.6/json/__init__.py\", line 299, in load\n    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)\n  File \"/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python3.6/json/__init__.py\", line 354, in loads\n    return _default_decoder.decode(s)\n  File \"/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python3.6/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python3.6/json/decoder.py\", line 357, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\njson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n", "args": {"verbose": false, "version": false, "profile": false, "profile_sort": "cumtime", "profile_count": 20, "command_name": "wait", "timeout": null, "tests": [], "out_mode": null}, "config": {"config_dirs": ["/yellow/usr/projects/hpctools/jgreen/pav2-lanl"], "user_config": false, "working_dir": "/users/jgreen/.pavilion/working_dir", "spack_path": null, "disable_plugins": [], "shared_group": null, "umask": "2", "build_threads": 4, "log_format": "{asctime}, {levelname}, {hostname}, {name}: {message}", "log_level": "info", "result_log": "/users/jgreen/.pavilion/working_dir/results.log", "flatten_results": true, "exception_log": "/users/jgreen/.pavilion/working_dir/exceptions.log", "wget_timeout": 5, "proxies": {}, "no_proxy": [], "env_setup": [], "default_results": {}, "pav_cfg_file": null, "pav_root": "/yellow/usr/projects/hpctest/pav2-next/src", "pav_vars": {"month": "3", "time": "13:25:22.010783", "day": "3", "year": "2021", "version": "2.3", "weekday": "Wednesday", "user": "jgreen", "timestamp": "1614803125.9738772"}}}

**Comment by kjeverson** [comment]
```
Traceback (most recent call last):
  File "/yellow/usr/projects/hpctest/pav2-next/src/bin/pav.py", line 143, in run_cmd
    sys.exit(cmd.run(pav_cfg, args))
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/wait.py", line 77, in run
    self.wait(pav_cfg, tests, end_time, args.out_mode)
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/plugins/commands/wait.py", line 95, in wait
    test_obj = TestRun.load(pav_cfg, test_id)
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/test_run.py", line 576, in load
    config = cls._load_config(path)
  File "/yellow/usr/projects/hpctest/pav2-next/src/lib/pavilion/test_run.py", line 735, in _load_config
    return json.load(config_file)
  File "/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python3.6/json/init.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python3.6/json/init.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lib/perceus/vnfs/asc-fe/rootfs/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
