### ISSUE TITLE
filter_test_run() got an unexpected keyword argument 'rslte'.

### ISSUE THREAD

**Issue by coneheadusa** [hpc/pavilion2#426]
"pav status"   throws this error after a fresh install today:

Unknown error running command status: filter_test_run() got an unexpected keyword argument 'rslte'.
Traceback (most recent call last):
  File "/u/Randall.Smith/pavilion/src/pavilion2/bin/pav.py", line 151, in run_cmd
    sys.exit(cmd.run(pav_cfg, args))
  File "/u/Randall.Smith/pavilion/src/pavilion2/lib/pavilion/plugins/commands/status.py", line 53, in run
    test_ids = cmd_utils.arg_filtered_tests(pav_cfg, args, verbose=self.errfile)
  File "/u/Randall.Smith/pavilion/src/pavilion2/lib/pavilion/cmd_utils.py", line 92, in arg_filtered_tests
    limit=limit).data
  File "/u/Randall.Smith/pavilion/src/pavilion2/lib/pavilion/dir_db.py", line 361, in select
    if not filter_func(data):
TypeError: filter_test_run() got an unexpected keyword argument 'rslte'

**Comment by Paul-Ferrell** [comment]
This has been fixed, but waiting on a code review.  Should be merged soon.
