### ISSUE TITLE
Pavilion marks test status as RESULTS when run script fails

### ISSUE THREAD

**Issue by tygoetsch** [hpc/pavilion2#528]
My run script failed (I messed up a path to an input file), but instead of getting ERROR when i run `pav status`, the state is `RESULTS` and `pav results -f 1722` gives me the following traceback.
```bash
-bash-4.2$ pav results -f 1722
Unknown error running command results: 'finished'.
Traceback (most recent call last):
  File "/yellow/usr/projects/hpctest/pavilion/2.4/src/bin/pav.py", line 91, in run_cmd
    sys.exit(cmd.run(pav_cfg, args))
  File "/yellow/usr/projects/hpctest/pavilion/2.4/src/lib/pavilion/commands/result.py", line 134, in run
    rslt['finished'], fullstamp=True)
KeyError: 'finished'
Traceback logged to None
```
`pav log run 1722` provides the reason for failure:
```bash
-bash-4.2$ pav log run 1722
File nohpoly not found
srun: error: fg009: tasks 0-31: Exited with exit code 1
**** END OF TEST *****
```

**Comment by tygoetsch** [comment]
Closing due to age.
