### ISSUE TITLE
Error filtering tests

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#529]
Traceback (most recent call last):
  File "/yellow/usr/projects/hpctest/pavilion/2.4/src/bin/pav.py", line 91, in run_cmd
    sys.exit(cmd.run(pav_cfg, args))
  File "/yellow/usr/projects/hpctest/pavilion/2.4/src/lib/pavilion/commands/status.py", line 71, in run
    tests = cmd_utils.get_tests_by_paths(pav_cfg, test_paths, self.errfile)
  File "/yellow/usr/projects/hpctest/pavilion/2.4/src/lib/pavilion/cmd_utils.py", line 293, in get_tests_by_paths
    output.fprint(sys.stdout, "No test at path: {}".format(test_path))
NameError: name 'sys' is not defined
Traceback logged to None

**Comment by Paul-Ferrell** [comment]
Already fixed.
