### ISSUE TITLE
Nonetype has no attribute groups

### ISSUE THREAD

**Issue by vsoch** [hpc/pavilion2#539]
I'm trying to set this up and reproduce the most basic stuffs from the documentation. I can do pvc show config (and I see output) but when I do `pav show tests`

```bash
Missing or duplicate label '<not_defined>' for config path '/code/config.yaml'.
Using label 'lbl1'
Could not find a pavilion config file. Using an empty/default config.
Missing or duplicate label '<not_defined>' for config path '/code/config.yaml'. Using label 'lbl1'
Unknown error running command show: Error in system variables
  Error getting value for system plugin sys_name
    'NoneType' object has no attribute 'groups'.
Traceback (most recent call last):
  File "/code/lib/pavilion/sys_vars/base_classes.py", line 187, in get
    values = self._get()
  File "/code/lib/pavilion/sys_vars/sys_name.py", line 25, in _get
    name = match.groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/lib/pavilion/resolver.py", line 66, in __init__
    self.base_var_man.add_var_set(
  File "/code/lib/pavilion/variables.py", line 85, in add_var_set
    var_set = VariableSet(name, value_dict=value_dict)
  File "/code/lib/pavilion/variables.py", line 762, in __init__
    self._init_from_config(value_dict)
  File "/code/lib/pavilion/variables.py", line 771, in _init_from_config
    for key, value in value_dict.items():
  File "/code/lib/pavilion/sys_vars/base_classes.py", line 87, in items
    return [(key, self[key]) for key in self.keys()]
  File "/code/lib/pavilion/sys_vars/base_classes.py", line 87, in <listcomp>
    return [(key, self[key]) for key in self.keys()]
  File "/code/lib/pavilion/sys_vars/base_classes.py", line 62, in __getitem__
    self.data[name] = plugin.get(defer=self.defer)
  File "/code/lib/pavilion/sys_vars/base_classes.py", line 189, in get
    raise SystemPluginError(
pavilion.sys_vars.base_classes.SystemPluginError: Error getting value for system plugin sys_name: 'NoneType' object has no attribute 'groups'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/lib/pavilion/main.py", line 103, in run_cmd
    sys.exit(cmd.run(pav_cfg, args))
  File "/code/lib/pavilion/commands/show.py", line 362, in run
    return self._run_sub_command(pav_cfg, args)
  File "/code/lib/pavilion/commands/base_classes.py", line 220, in _run_sub_command
    cmd_result = self.sub_cmds[cmd_name](self, pav_cfg, args)
  File "/code/lib/pavilion/commands/show.py", line 837, in _tests_cmd
    resolv = resolver.TestConfigResolver(pav_cfg)
  File "/code/lib/pavilion/resolver.py", line 70, in __init__
    raise TestConfigError(
pavilion.errors.TestConfigError: Error in system variables
  Error getting value for system plugin sys_name
    'NoneType' object has no attribute 'groups'
Traceback logged to None
```

I'm following the tutorial here: https://pavilion2.readthedocs.io/en/latest/tutorials/basic_pavilion.html#install-pavilion

**Comment by Paul-Ferrell** [comment]
You have found a bug in the sys_name variable plugin. Yay! 

Out of curiosity, what's the name (`hostname -s`) of the system you're running on? 

This is fixed in PR #540. I'll merge it as soon as the unit tests pass.
