### ISSUE TITLE
Permission fails in the 'clean' command should be told to the user. 

### ISSUE THREAD

**Issue by Paul-Ferrell** [hpc/pavilion2#69]
tt-fey1:lapid $ pav clean
Removing Tests...
Unknown error running command clean: [Errno 13] Permission denied: 'requests'.
Traceback (most recent call last):
  File "/usr/projects/hpctest/pav2/src/bin/pav.py", line 152, in main
    sys.exit(cmd.run(pav_cfg, args))
  File "/usr/projects/hpctest/pav2/src/lib/pavilion/plugins/commands/clean.py", line 82, in run
    shutil.rmtree((tests_dir/test).as_posix())
  File "/usr/lib64/python3.4/shutil.py", line 468, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib64/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.4/shutil.py", line 406, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib64/python3.4/shutil.py", line 426, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib64/python3.4/shutil.py", line 424, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'requests'
Traceback saved in /users/lapid/.pavilion/tracebacks/6583

**Comment by Paul-Ferrell** [comment]
This is still an issue.

**Comment by Paul-Ferrell** [comment]
This is still an issue.
